#-------------------------------
# General Site Settings

menu:

- {name: 'À propos',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'El natura',   url: 'proj-1'}
- {name: 'Émotion',   url: 'proj-2'}
- {name: 'Elucitrap',   url: 'proj-3'}
- {name: 'Reconstruction site promis',  url: 'proj-4'}



#-------------------------------
# Contact Section

social:

- {icon: 'instagram', link: 'https://www.instagram.com/_lauriehoude/?igshid=dzVrcXJtaHMyeHdq&utm_source=qr'}
- {icon: 'github',    link: 'https://github.com/lauriehoude'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/laurie-houde?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app'}
- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.lauriehoude12@outlook.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
